<?php

use App\Models\Product;
use App\Models\ProductAsset;
use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

beforeEach(function () {
    Storage::fake('public');
});

test('user can upload an image asset and thumbnail is generated', function () {
    $user = User::factory()->create();
    $product = Product::factory()->for($user)->create();

    $file = UploadedFile::fake()->image('hero.jpg', 800, 600);

    $response = $this->actingAs($user)->post(
        route('product-assets.store', $product),
        ['files' => [$file]]
    );

    $response->assertRedirect();

    $asset = ProductAsset::firstOrFail();
    expect($asset->product_id)->toBe($product->id);
    expect($asset->uploaded_by)->toBe($user->id);
    expect($asset->mime)->toBe('image/jpeg');
    expect($asset->type)->toBe('image');
    Storage::disk('public')->assertExists($asset->path);

    // Thumbnail is generated by GD; assert path is set and file exists.
    expect($asset->thumbnail_path)->not->toBeNull();
    Storage::disk('public')->assertExists($asset->thumbnail_path);
});

test('rejects non-whitelisted MIME types with 422', function () {
    $user = User::factory()->create();
    $product = Product::factory()->for($user)->create();

    $exe = UploadedFile::fake()->create('payload.exe', 100, 'application/octet-stream');

    $response = $this->actingAs($user)
        ->postJson(
            route('product-assets.store', $product),
            ['files' => [$exe]]
        );

    $response->assertStatus(422);
    expect(ProductAsset::count())->toBe(0);
});

test('user can delete their own asset', function () {
    $user = User::factory()->create();
    $product = Product::factory()->for($user)->create();

    Storage::disk('public')->put('products/' . $product->id . '/test.jpg', 'fake');
    $asset = ProductAsset::factory()->for($product)->create([
        'uploaded_by' => $user->id,
        'disk' => 'public',
        'path' => 'products/' . $product->id . '/test.jpg',
        'thumbnail_path' => null,
    ]);

    $response = $this->actingAs($user)->delete(
        route('product-assets.destroy', ['product' => $product, 'asset' => $asset])
    );

    $response->assertRedirect();
    expect(ProductAsset::find($asset->id))->toBeNull();
    Storage::disk('public')->assertMissing('products/' . $product->id . '/test.jpg');
});
